[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info
childlogdir=/var/log/supervisor

[include]
files = /etc/supervisor/conf.d/*.conf

# [program:dispatch-due-images-worker]
# command=bash -c 'while true; do php /var/www/html/artisan subjects:check-due-images; sleep 300; done'
# autostart=true
# autorestart=true
# user=www-data
# redirect_stderr=true
# stdout_logfile=/var/www/html/storage/logs/dispatch-due-images-worker.log
# stdout_logfile_maxbytes=0